In [69]:
%pip install ipdb

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 780 kB 2.5 MB/s ta 0:00:01
  Created wheel for ipdb: filename=ipdb-0.13.4-py3-none-any.whl size=10972 sha256=7be9e1a62bd1f5194e6a8bf8f31125d997b7725027bb33fe980760cb9c059aaf
  Stored in directory: /tmp/xdg_cache/pip/wheels/3c/8b/69/d218d414a5b6262da8254659e6908c1a6afedb0804eed73f35
Successfully built ipdb
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.


In [50]:
from argparse import Namespace

In [ ]:
#####################################
# Создание сегментационного датасета
#####################################

In [51]:
# import scripts.create_segmentation_dataset

# request = Namespace(
#     data_dir='data/data',
# )
# scripts.create_segmentation_dataset.main(request)

In [52]:
########################################
# Запуск обучения сегментационной модели
########################################

100%|██████████| 25633/25633 [12:11<00:00, 35.03it/s]


In [70]:
from scripts.train_segmentation import main

request = Namespace(
    data_path='data/data',
    epochs=10,
    batch_size=80, #128,
    image_size=256,
    lr=3e-4,
    weight_decay=1e-6,
    lr_step=None,
    lr_gamma=None,
    weight_bce=1,
    load=None, # 'baseline_models/segmentation_10ep.pth',
    output_dir='runs/baseline_segmentation'
)

In [71]:
main(request)

2021-09-04 13:02:07 Start training with params:
2021-09-04 13:02:07 Argument batch_size: 80
2021-09-04 13:02:07 Argument data_path: 'data/data'
2021-09-04 13:02:07 Argument epochs: 10
2021-09-04 13:02:07 Argument image_size: 256
2021-09-04 13:02:07 Argument load: None
2021-09-04 13:02:07 Argument lr: 0.0003
2021-09-04 13:02:07 Argument lr_gamma: None
2021-09-04 13:02:07 Argument lr_step: None
2021-09-04 13:02:07 Argument output_dir: 'runs/baseline_segmentation'
2021-09-04 13:02:07 Argument weight_bce: 1
2021-09-04 13:02:07 Argument weight_decay: 1e-06
Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /tmp/xdg_cache/torch/hub/checkpoints/resnet34-333f7ec4.pth


2021-09-04 13:02:10 Model type: Unet
2021-09-04 13:02:11 Length of train / val = 20505 / 5127
2021-09-04 13:02:11 Number of batches of train / val = 256 / 65
2021-09-04 13:02:11 Starting epoch 1/10.
  0%|          | 0/256 [00:00<?, ?it/s]

> /home/jupyter/work/resources/contest02/scripts/train_segmentation.py(61)train()
     60 
---> 61         bce_loss_value, dice_loss_value = criterion(masks_probs.cpu().view(-1), true_masks.view(-1))
     62         loss = bce_loss_value + dice_loss_value



ipdb>  imgs.shape


torch.Size([80, 3, 256, 256])


ipdb>  masks_pred.shape


torch.Size([80, 1, 256, 256])


ipdb>  masks_pred


tensor([[[[-1.4205e-01, -4.0415e-01, -3.3979e-01,  ..., -6.8617e-01,
           -5.0800e-01, -2.1706e-01],
          [-8.4388e-02, -3.9936e-01,  7.2037e-02,  ..., -7.2222e-02,
           -3.0395e-01, -5.2652e-01],
          [ 4.5582e-02, -5.8081e-01, -6.5336e-01,  ..., -5.2057e-01,
           -7.5298e-01, -4.5936e-01],
          ...,
          [-1.6065e-01, -5.1555e-01, -2.8096e-01,  ...,  1.1146e+00,
            7.7200e-01, -1.0990e-01],
          [-4.5038e-01, -3.7593e-01, -1.5018e-01,  ...,  2.3519e-01,
            2.1529e-01, -1.6386e-01],
          [ 2.1941e-01,  6.0965e-04, -8.2790e-02,  ..., -1.0740e-01,
           -7.0906e-02,  1.0163e-01]]],


        [[[-5.5357e-02, -5.9253e-01, -5.6010e-01,  ..., -5.9212e-01,
           -3.4106e-01, -2.3630e-01],
          [ 1.4555e-01, -4.6729e-02,  1.8350e-01,  ...,  4.5651e-02,
           -2.8328e-01, -6.6028e-01],
          [ 1.2142e-01, -6.7915e-01, -5.5112e-01,  ..., -9.1579e-02,
           -8.1721e-01, -6.1613e-01],
          ...,
   

ipdb>  masks_probs


tensor([[[[0.4645, 0.4003, 0.4159,  ..., 0.3349, 0.3757, 0.4459],
          [0.4789, 0.4015, 0.5180,  ..., 0.4820, 0.4246, 0.3713],
          [0.5114, 0.3587, 0.3422,  ..., 0.3727, 0.3202, 0.3871],
          ...,
          [0.4599, 0.3739, 0.4302,  ..., 0.7530, 0.6840, 0.4726],
          [0.3893, 0.4071, 0.4625,  ..., 0.5585, 0.5536, 0.4591],
          [0.5546, 0.5002, 0.4793,  ..., 0.4732, 0.4823, 0.5254]]],


        [[[0.4862, 0.3561, 0.3635,  ..., 0.3561, 0.4156, 0.4412],
          [0.5363, 0.4883, 0.5457,  ..., 0.5114, 0.4297, 0.3407],
          [0.5303, 0.3365, 0.3656,  ..., 0.4771, 0.3064, 0.3507],
          ...,
          [0.4185, 0.5188, 0.5007,  ..., 0.5902, 0.6133, 0.4644],
          [0.3701, 0.5295, 0.5809,  ..., 0.4690, 0.4376, 0.4617],
          [0.5527, 0.5277, 0.4601,  ..., 0.4922, 0.4380, 0.4927]]],


        [[[0.4489, 0.4396, 0.4568,  ..., 0.3834, 0.4258, 0.4247],
          [0.4865, 0.4149, 0.4900,  ..., 0.4964, 0.4762, 0.2860],
          [0.5431, 0.4357, 0.4262,  ..

ipdb>  masks_probs.shape


torch.Size([80, 1, 256, 256])


ipdb>  masks_probs.cpu().view(-1)


tensor([0.4645, 0.4003, 0.4159,  ..., 0.5036, 0.4004, 0.5096],
       grad_fn=<ViewBackward>)


ipdb>  masks_probs.cpu().view(-1).shape


torch.Size([5242880])


ipdb>  criterion2(masks_probs.cpu().view(-1), true_masks.view(-1))


*** RuntimeError: Boolean value of Tensor with more than one value is ambiguous


ipdb>  pred=masks_probs.cpu().view(-1)
ipdb>  ground=true_masks.view(-1)
ipdb>  pred.shape


torch.Size([5242880])


ipdb>  ground.shape


torch.Size([5242880])


ipdb>  nn.BCELoss()(pred, ground)


tensor(0.8375, grad_fn=<BinaryCrossEntropyBackward>)


ipdb>  nn.BCEloss()


*** AttributeError: module 'torch.nn' has no attribute 'BCEloss'


ipdb>  nn.BCELoss(pred, ground)


*** RuntimeError: Boolean value of Tensor with more than one value is ambiguous


ipdb>  loss = nn.BCELoss()
ipdb>  loss(pred, ground)


tensor(0.8375, grad_fn=<BinaryCrossEntropyBackward>)


ipdb>  quit


  0%|          | 0/256 [20:07<?, ?it/s]


BdbQuit: 